GET http://localhost:8080/api/basic/getSameClassificationPercentage
Accept: application/json

###
GET http://localhost:8080/api/basic/getRanking?countries=all&classifications=Computer science&start=1900&end=2022&limit=12
Accept: application/json

###
GET http://localhost:8080/api/basic/getRanking?countries=UnitedStates&countries=China&classifications=Computer science&start=1900&end=2022&limit=12
Accept: application/json

###
GET http://localhost:8080/api/basic/getAllClassification
Accept: application/json

###
GET http://localhost:8080/api/basic/getAllCountry
Accept: application/json

###
GET http://localhost:8080/api/country/getKnowledgeFlowOut?country=UnitedStates&start=1900&end=1950
Accept: application/json

###
GET http://localhost:8080/api/country/getSingleCountryCountLine?country=UnitedStates&start=1900&end=1950
Accept: application/json

###
GET http://localhost:8080/api/basic/get?id=35